### PR TITLE
Put default filter of showing only recently verified resources #17

### PR DESCRIPTION
**Pull request by codelear**
added checkbox to filter data verified in the last 2 hours

image

### CODE REVIEW

**Comment by Godwindaniel10** [comment]
hi @codelear 

I would like to work on this issue, but can you be more clear on the issue?

**Comment by codelear** [comment]
@Godwindaniel10 this is not an issue i created. I forked from hargup/covidsupport and the issue is defined there. This is just a fix for that issue. I also created a PR for that issue on hargup/covidsupport

**Comment by codelear** [comment]
maybe i should remove the label. it is misleading.

**Comment by codelear** [comment]
merged in hargup/covidsupport

**Pull request closed without merging**
